### ISSUE TITLE
Fldigi fork?

### ISSUE THREAD

**Issue by AsciiWolf** [w1hkj/fldigi#16]
The Fldigi development seems to have stalled with no commits or other changes being made since January 2019. I think that, if the current upstream is not active anymore, it could be a good idea to consider making a fork of this project to continue further development and implement new features (including things like [AppImage support](https://github.com/w1hkj/fldigi/issues/7) or new digital modes). Unfortunately, I don't have enough free time to afford making and maintaining this fork myself.

**Comment by rikvanriel** [comment]
Fldigi development has been happening, just in a different (and maybe slightly inconvenient, since we cannot file pull requests) location:

https://sourceforge.net/p/fldigi/fldigi/ci/master/tree/

**Comment by AsciiWolf** [comment]
That is a good news, thanks! :-)
